# Site settings
author: Giacomo Vagni
title: Mismeasure of things
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url:  "http://giacomovagni.github.io"  # baseurl: "/knitr-jekyll" the subpath of your site, e.g. "/blog". For explanation, see https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/  
baseurl: "/motsetchoses" 
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
